modLoader="javafml"
loaderVersion="[28,)"

[[mods]]
modId="gregormodmaster"
version="1.0.0"
displayName="Gregor mod master"
credits="Created using mod maker MCreator - https://mcreator.net/about"
displayURL="https://mcreator.net"
authors="Admin, MCreator"

[[dependencies.gregormodmaster]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.14.4]"
    ordering="NONE"
    side="BOTH"



